# Generated by Django 2.2.7 on 2020-06-19 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_page_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_body', models.TextField(default='')),
                ('post_created_on', models.DateTimeField(auto_now_add=True)),
                ('post_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
