# Generated by Django 2.2.7 on 2020-06-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialite', '0002_home_page_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page_post',
            name='post_body',
            field=models.CharField(max_length=100),
        ),
    ]
