# Generated by Django 2.2.7 on 2020-06-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialite', '0008_auto_20200620_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
