# Generated by Django 2.2.7 on 2020-06-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialite', '0009_auto_20200620_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
