# Generated by Django 2.2.7 on 2020-06-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialite', '0012_auto_20200622_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='slug',
            field=models.SlugField(default='', max_length=120),
        ),
    ]
