# Generated by Django 2.2.7 on 2020-06-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialite', '0013_user_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='slug',
        ),
    ]
